-- Generated by the Organizer Library (Sun Jun  2 21:55:48 2019)
return {
    [1]={
        ["log_name"]="blood finger gauntlets", 
        ["id"]=14059, 
        ["name"]="blood fng. gnt.", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="trotter boots", 
        ["id"]=15736, 
        ["name"]="trotter boots", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="seiryu's kote", 
        ["id"]=12690, 
        ["name"]="seiryu's kote", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="suzaku's sune-ate", 
        ["id"]=12946, 
        ["name"]="suzaku's sune-ate", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="dusk ledelsens +1", 
        ["id"]=14188, 
        ["name"]="dusk ledelsens +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="hachiryu sune-ate", 
        ["id"]=11364, 
        ["name"]="hachiryu sune-ate", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="dusk gloves +1", 
        ["id"]=14825, 
        ["name"]="dusk gloves +1", 
        ["count"]=1
    }
}