-- Generated by the Organizer Library (Wed Jun  6 23:22:33 2018)
return {
    [1]={
        ["log_name"]="bibiki seashell", 
        ["id"]=18257, 
        ["name"]="bibiki seashell", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="marine f gloves", 
        ["id"]=14834, 
        ["name"]="marine f gloves", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="homam gambieras", 
        ["id"]=15661, 
        ["name"]="homam gambieras", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="kaiser schuhs", 
        ["id"]=14163, 
        ["name"]="kaiser schuhs", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sturm's report", 
        ["id"]=18734, 
        ["name"]="sturm's report", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="homam manopolas", 
        ["id"]=14905, 
        ["name"]="homam manopolas", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="koenig handschuhs", 
        ["id"]=12677, 
        ["name"]="kng. handschuhs", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="fenrir's stone", 
        ["id"]=18165, 
        ["name"]="fenrir's stone", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="heavy gauntlets", 
        ["id"]=14886, 
        ["name"]="heavy gauntlets", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dusk gloves +1", 
        ["id"]=14825, 
        ["name"]="dusk gloves +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="hecatomb leggings +1", 
        ["id"]=14181, 
        ["name"]="hct. leggings +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="hecatomb mittens +1", 
        ["id"]=14077, 
        ["name"]="hct. mittens +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="tarasque mitts +1", 
        ["id"]=14074, 
        ["name"]="tarasque mitts +1", 
        ["count"]=1
    }
}