-- Generated by the Organizer Library (Wed May 29 23:20:31 2019)
return {
    [1]={
        ["log_name"]="barbarossa's moufles", 
        ["id"]=14943, 
        ["name"]="barb. moufles", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="enkidu's leggings", 
        ["id"]=11378, 
        ["name"]="enkidu's leggings", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="trotter boots", 
        ["id"]=15736, 
        ["name"]="trotter boots", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="bibiki seashell", 
        ["id"]=18257, 
        ["name"]="bibiki seashell", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="merman's leggings", 
        ["id"]=14111, 
        ["name"]="mmn. leggings", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="hecatomb mittens +1", 
        ["id"]=14077, 
        ["name"]="hct. mittens +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="dusk ledelsens +1", 
        ["id"]=14188, 
        ["name"]="dusk ledelsens +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="enkidu's mittens", 
        ["id"]=15023, 
        ["name"]="enkidu's mittens", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="white tathlum", 
        ["id"]=19213, 
        ["name"]="white tathlum", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="black tathlum", 
        ["id"]=19212, 
        ["name"]="black tathlum", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="bomb core", 
        ["id"]=18139, 
        ["name"]="bomb core", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="homam manopolas", 
        ["id"]=14905, 
        ["name"]="homam manopolas", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="homam gambieras", 
        ["id"]=15661, 
        ["name"]="homam gambieras", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="dusk gloves +1", 
        ["id"]=14825, 
        ["name"]="dusk gloves +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="fire bomblet", 
        ["id"]=18707, 
        ["name"]="fire bomblet", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="alkyoneus's bracelets", 
        ["id"]=14022, 
        ["name"]="alkyoneus's brc.", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="hecatomb leggings +1", 
        ["id"]=14181, 
        ["name"]="hct. leggings +1", 
        ["count"]=1
    }
}