-- Generated by the Organizer Library (03/09/18 18:42:50)
return {
    [1]={
        ["log_name"]="chocobo whistle", 
        ["id"]=15533, 
        ["name"]="chocobo whistle", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="warp ring", 
        ["id"]=28540, 
        ["name"]="warp ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="magnetic earring", 
        ["id"]=15963, 
        ["name"]="magnetic earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="nexus cape", 
        ["id"]=11538, 
        ["name"]="nexus cape", 
        ["count"]=1
    }, 
    [5]={
        ["id"]=18235, 
        ["name"]="corsair bullet", 
        ["count"]=99, 
        ["log_name"]="corsair bullet"
    }, 
    [6]={
        ["id"]=5342, 
        ["name"]="cor. bull. pouch", 
        ["count"]=12, 
        ["log_name"]="corsair bullet pouch"
    }, 
    [7]={
        ["id"]=2974, 
        ["name"]="trump card", 
        ["count"]=99, 
        ["log_name"]="trump card"
    }, 
    [8]={
        ["id"]=1179, 
        ["name"]="shihei", 
        ["count"]=99, 
        ["log_name"]="shihei"
    }, 
    [9]={
        ["id"]=4151, 
        ["name"]="echo drops", 
        ["count"]=12, 
        ["log_name"]="flask of echo drops"
    }, 
    [10]={
        ["id"]=5870, 
        ["name"]="trump card case", 
        ["count"]=12, 
        ["log_name"]="trump card case"
    }
}