-- Generated by the Organizer Library (02/20/18 23:56:41)
return {
    [1]={
        ["log_name"]="chocobo whistle", 
        ["id"]=15533, 
        ["name"]="chocobo whistle", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="etoile tights +1", 
        ["id"]=16361, 
        ["name"]="etoile tights +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="warp ring", 
        ["id"]=28540, 
        ["name"]="warp ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="etoile casaque +1", 
        ["id"]=11306, 
        ["name"]="etoile casaque +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="dancer's toe shoes +1", 
        ["id"]=11394, 
        ["name"]="dancer's shoes +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="dancer's tiara +1", 
        ["id"]=11476, 
        ["name"]="dancer's tiara +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="dancer's tights +1", 
        ["id"]=16358, 
        ["name"]="dancer's tights +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="magnetic earring", 
        ["id"]=15963, 
        ["name"]="magnetic earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="etoile tiara +1", 
        ["id"]=11479, 
        ["name"]="etoile tiara +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="etoile toe shoes +1", 
        ["id"]=11397, 
        ["name"]="etoile shoes +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="dancer's casaque +1", 
        ["id"]=11303, 
        ["name"]="dnc. casaque +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="etoile bangles +1", 
        ["id"]=15039, 
        ["name"]="etoile bangles +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="nexus cape", 
        ["id"]=11538, 
        ["name"]="nexus cape", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="dancer's bangles +1", 
        ["id"]=15036, 
        ["name"]="dnc. bangles +1", 
        ["count"]=1
    }
}