-- Generated by the Organizer Library (Wed May 29 20:08:56 2019)
return {
    [1]={
        ["log_name"]="chocobo whistle", 
        ["id"]=15533, 
        ["name"]="chocobo whistle", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="warp ring", 
        ["id"]=28540, 
        ["name"]="warp ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="saotome haidate", 
        ["id"]=15128, 
        ["name"]="saotome haidate", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="saotome kote", 
        ["id"]=15113, 
        ["name"]="saotome kote", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="magnetic earring", 
        ["id"]=15963, 
        ["name"]="magnetic earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="myochin kabuto", 
        ["id"]=13868, 
        ["name"]="myochin kabuto", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="nexus cape", 
        ["id"]=11538, 
        ["name"]="nexus cape", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="myochin sune-ate", 
        ["id"]=14100, 
        ["name"]="myochin sune-ate", 
        ["count"]=1
    }
}