-- Generated by the Organizer Library (Wed Jun  6 23:22:33 2018)
return {
    [1]={
        ["log_name"]="orochi nodowa +1", 
        ["id"]=15540, 
        ["name"]="orochi nodowa +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="shadow mantle", 
        ["id"]=13658, 
        ["name"]="shadow mantle", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="gigant mantle", 
        ["id"]=13648, 
        ["name"]="gigant mantle", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="cuchulain's mantle", 
        ["id"]=16241, 
        ["name"]="cuchulain's mantle", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fortitude torque", 
        ["id"]=15511, 
        ["name"]="fortitude torque", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="ritter gorget", 
        ["id"]=16267, 
        ["name"]="ritter gorget", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="cerberus mantle +1", 
        ["id"]=16216, 
        ["name"]="cerb. mantle +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="fortified chain", 
        ["id"]=15524, 
        ["name"]="fortified chain", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="gnole torque", 
        ["id"]=16283, 
        ["name"]="gnole torque", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="boxer's mantle", 
        ["id"]=15477, 
        ["name"]="boxer's mantle", 
        ["count"]=1
    }
}