-- Generated by the Organizer Library (02/21/18 19:48:16)
return {
    [1]={
        ["log_name"]="chivalrous chain", 
        ["id"]=15523, 
        ["name"]="chivalrous chain", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="spider torque", 
        ["id"]=13137, 
        ["name"]="spider torque", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="wivre gorget +1", 
        ["id"]=16266, 
        ["name"]="wivre gorget +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="dark torque", 
        ["id"]=13153, 
        ["name"]="dark torque", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="ancient torque", 
        ["id"]=16275, 
        ["name"]="ancient torque", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="lemegeton medallion +1", 
        ["id"]=11584, 
        ["name"]="lmg. medallion +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="shadow mantle", 
        ["id"]=13658, 
        ["name"]="shadow mantle", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="gigant mantle", 
        ["id"]=13648, 
        ["name"]="gigant mantle", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="merciful cape", 
        ["id"]=15471, 
        ["name"]="merciful cape", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="fortified chain", 
        ["id"]=15524, 
        ["name"]="fortified chain", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="bloodbead gorget", 
        ["id"]=16302, 
        ["name"]="bloodbead gorget", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="gnole torque", 
        ["id"]=16283, 
        ["name"]="gnole torque", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="prudence torque", 
        ["id"]=15510, 
        ["name"]="prudence torque", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="cerberus mantle +1", 
        ["id"]=16216, 
        ["name"]="cerb. mantle +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="ritter gorget", 
        ["id"]=16267, 
        ["name"]="ritter gorget", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="cuchulain's mantle", 
        ["id"]=16241, 
        ["name"]="cuchulain's mantle", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="orochi nodowa", 
        ["id"]=15539, 
        ["name"]="orochi nodowa", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="justice torque", 
        ["id"]=15508, 
        ["name"]="justice torque", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="abyss cape", 
        ["id"]=15479, 
        ["name"]="abyss cape", 
        ["count"]=1
    }
}