-- Generated by the Organizer Library (Wed Jun 19 21:47:25 2019)
return {
    [1]={
        ["log_name"]="alkalurops", 
        ["id"]=18593, 
        ["name"]="alkalurops", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="prism cape", 
        ["count"]=1, 
        ["id"]=13627, 
        ["name"]="prism cape", 
        ["augments"]={
            [1]="\"Fast Cast\"+3"
        }
    }, 
    [3]={
        ["log_name"]="prism cape", 
        ["count"]=1, 
        ["id"]=13627, 
        ["name"]="prism cape", 
        ["augments"]={
            [1]="Mag. Acc.+4"
        }
    }, 
    [4]={
        ["log_name"]="prism cape", 
        ["count"]=1, 
        ["id"]=13627, 
        ["name"]="prism cape", 
        ["augments"]={
            [1]="Spell interruption rate down -20%"
        }
    }, 
    [5]={
        ["log_name"]="prism cape", 
        ["count"]=1, 
        ["id"]=13627, 
        ["name"]="prism cape", 
        ["augments"]={
            [1]="\"Cure\" potency +4%"
        }
    }, 
    [6]={
        ["log_name"]="spider torque", 
        ["id"]=13137, 
        ["name"]="spider torque", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="orochi nodowa +1", 
        ["id"]=15540, 
        ["name"]="orochi nodowa +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="shadow mantle", 
        ["id"]=13658, 
        ["name"]="shadow mantle", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="gigant mantle", 
        ["id"]=13648, 
        ["name"]="gigant mantle", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="terra's staff", 
        ["id"]=17552, 
        ["name"]="terra's staff", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="crook", 
        ["id"]=19382, 
        ["name"]="crook", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="chatoyant staff", 
        ["id"]=18633, 
        ["name"]="chatoyant staff", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="seveneyes", 
        ["id"]=18847, 
        ["name"]="seveneyes", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="bloodbead gorget", 
        ["id"]=16302, 
        ["name"]="bloodbead gorget", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="lemegeton medallion +1", 
        ["id"]=11584, 
        ["name"]="lmg. medallion +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="fylgja torque +1", 
        ["id"]=11580, 
        ["name"]="fylgja torque +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="dark torque", 
        ["id"]=13153, 
        ["name"]="dark torque", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="gnole torque", 
        ["id"]=16283, 
        ["name"]="gnole torque", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="merciful cape", 
        ["id"]=15471, 
        ["name"]="merciful cape", 
        ["count"]=1
    }
}