-- Generated by the Organizer Library (Sun Jun  2 21:55:48 2019)
return {
    [1]={
        ["log_name"]="kirin's osode", 
        ["id"]=12562, 
        ["name"]="kirin's osode", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="blood cuisses", 
        ["id"]=14281, 
        ["name"]="blood cuisses", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="avalon breastplate", 
        ["id"]=11286, 
        ["name"]="avalon breastplate", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ninurta's sash", 
        ["id"]=15458, 
        ["name"]="ninurta's sash", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="dusk trousers +1", 
        ["id"]=14307, 
        ["name"]="dusk trousers +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="hachiryu haramaki", 
        ["id"]=11281, 
        ["name"]="hachiryu haramaki", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="scout's belt", 
        ["id"]=15876, 
        ["name"]="scout's belt", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="scorpion harness +1", 
        ["count"]=1, 
        ["id"]=13734, 
        ["name"]="scp. harness +1", 
        ["augments"]={
            [1]="Haste+11"
        }
    }, 
    [9]={
        ["log_name"]="trance belt", 
        ["id"]=15895, 
        ["name"]="trance belt", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="enkidu's harness", 
        ["id"]=11284, 
        ["name"]="enkidu's harness", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="resolute belt", 
        ["id"]=15887, 
        ["name"]="resolute belt", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="kyudogi +1", 
        ["id"]=14540, 
        ["name"]="kyudogi +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="byakko's haidate", 
        ["id"]=12818, 
        ["name"]="byakko's haidate", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="hachiryu haidate", 
        ["id"]=16337, 
        ["name"]="hachiryu haidate", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="buccaneer's belt", 
        ["id"]=15911, 
        ["name"]="buccaneer's belt", 
        ["count"]=1
    }
}