-- Generated by the Organizer Library (02/18/18 01:36:55)
return {
    [1]={
        ["log_name"]="arhat's gi +1", 
        ["id"]=13802, 
        ["name"]="arhat's gi +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="swordbelt +1", 
        ["id"]=13232, 
        ["name"]="swordbelt +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="lycopodium sash", 
        ["id"]=15928, 
        ["name"]="lycopodium sash", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="resolute belt", 
        ["id"]=15887, 
        ["name"]="resolute belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="avalon breastplate", 
        ["id"]=11286, 
        ["name"]="avalon breastplate", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="hachiryu haramaki", 
        ["id"]=11281, 
        ["name"]="hachiryu haramaki", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="hachiryu haidate", 
        ["id"]=16337, 
        ["name"]="hachiryu haidate", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="trance belt", 
        ["id"]=15895, 
        ["name"]="trance belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="kyudogi +1", 
        ["id"]=14540, 
        ["name"]="kyudogi +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="byrnie +1", 
        ["id"]=13741, 
        ["name"]="byrnie +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="darksteel subligar +1", 
        ["id"]=14234, 
        ["name"]="dst. subligar +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="kirin's osode", 
        ["id"]=12562, 
        ["name"]="kirin's osode", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="hachiman domaru +1", 
        ["id"]=14439, 
        ["name"]="hmn. domaru +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="byakko's haidate", 
        ["id"]=12818, 
        ["name"]="byakko's haidate", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="velocious belt", 
        ["id"]=15899, 
        ["name"]="velocious belt", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="buccaneer's belt", 
        ["id"]=15911, 
        ["name"]="buccaneer's belt", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="shinimusha hara-ate", 
        ["id"]=14404, 
        ["name"]="shm. hara-ate", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="oily trousers", 
        ["id"]=16344, 
        ["name"]="oily trousers", 
        ["count"]=1
    }
}