-- Generated by the Organizer Library (02/21/18 19:48:16)
return {
    [1]={
        ["log_name"]="homam cosciales", 
        ["id"]=15576, 
        ["name"]="homam cosciales", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="armada hauberk", 
        ["id"]=14371, 
        ["name"]="armada hauberk", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="warwolf belt", 
        ["id"]=15294, 
        ["name"]="warwolf belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="resolute belt", 
        ["id"]=15887, 
        ["name"]="resolute belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="aurum cuirass", 
        ["id"]=11282, 
        ["name"]="aurum cuirass", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="blood cuisses", 
        ["id"]=14281, 
        ["name"]="blood cuisses", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="jet seraweels", 
        ["id"]=15613, 
        ["name"]="jet seraweels", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="buccaneer's belt", 
        ["id"]=15911, 
        ["name"]="buccaneer's belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="trance belt", 
        ["id"]=15895, 
        ["name"]="trance belt", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="gloom breastplate", 
        ["id"]=14409, 
        ["name"]="gloom breastplate", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="demon's harness", 
        ["id"]=13767, 
        ["name"]="demon's harness", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="dusk trousers +1", 
        ["id"]=14307, 
        ["name"]="dusk trousers +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="onyx cuisses", 
        ["id"]=15401, 
        ["name"]="onyx cuisses", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="darksteel subligar +1", 
        ["id"]=14234, 
        ["name"]="dst. subligar +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="ocean stone", 
        ["id"]=13256, 
        ["name"]="ocean stone", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="valhalla breastplate", 
        ["id"]=14577, 
        ["name"]="valhalla brstplate", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="velocious belt", 
        ["id"]=15899, 
        ["name"]="velocious belt", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="scorpion harness +1", 
        ["count"]=1, 
        ["id"]=13734, 
        ["name"]="scp. harness +1", 
        ["augments"]={
            [1]="Haste+11"
        }
    }, 
    [19]={
        ["log_name"]="corselet", 
        ["id"]=14544, 
        ["name"]="corselet", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="crimson scale mail", 
        ["id"]=14367, 
        ["name"]="crm. scale mail", 
        ["count"]=1
    }
}