-- Generated by the Organizer Library (02/18/18 16:01:46)
return {
    [1]={
        ["log_name"]="maat's cap", 
        ["id"]=15194, 
        ["name"]="maat's cap", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="zha'go's barbut", 
        ["id"]=16159, 
        ["name"]="zha'go's barbut", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="gnole crown", 
        ["id"]=11483, 
        ["name"]="gnole crown", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="drone earring", 
        ["id"]=13361, 
        ["name"]="drone earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="drone earring", 
        ["id"]=13361, 
        ["name"]="drone earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="moldavite earring", 
        ["id"]=14724, 
        ["name"]="moldavite earring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="morion earring +1", 
        ["id"]=14721, 
        ["name"]="morion earring +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dragon ring +1", 
        ["id"]=14627, 
        ["name"]="dragon ring +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="walahra turban", 
        ["id"]=15270, 
        ["name"]="walahra turban", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="merman's earring", 
        ["id"]=13406, 
        ["name"]="merman's earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="merman's earring", 
        ["id"]=13406, 
        ["name"]="merman's earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="snow ring", 
        ["id"]=14640, 
        ["name"]="snow ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="strigoi ring", 
        ["id"]=11628, 
        ["name"]="strigoi ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="omega ring", 
        ["id"]=15800, 
        ["name"]="omega ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="veela ring", 
        ["id"]=11634, 
        ["name"]="veela ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="gnadbhod's helm", 
        ["id"]=16158, 
        ["name"]="gnadbhod's helm", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="genbu's kabuto", 
        ["id"]=12434, 
        ["name"]="genbu's kabuto", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="hades earring +1", 
        ["id"]=14718, 
        ["name"]="hades earring +1", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="jelly ring", 
        ["id"]=13303, 
        ["name"]="jelly ring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="novia earring", 
        ["id"]=14809, 
        ["name"]="novia earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="toreador's ring", 
        ["count"]=1, 
        ["id"]=14674, 
        ["name"]="toreador's ring", 
        ["augments"]={
            [1]="Accuracy+5", 
            [2]="\"Triple Atk.\"+2"
        }
    }, 
    [26]={
        ["log_name"]="toreador's ring", 
        ["count"]=1, 
        ["id"]=14674, 
        ["name"]="toreador's ring", 
        ["augments"]={
            [1]="\"Triple Atk.\"+2", 
            [2]="Accuracy+4"
        }
    }, 
    [27]={
        ["log_name"]="arhat's jinpachi +1", 
        ["id"]=13886, 
        ["name"]="arh. jinpachi +1", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="behemoth ring +1", 
        ["id"]=13556, 
        ["name"]="behemoth ring +1", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="corneus ring", 
        ["id"]=11630, 
        ["name"]="corneus ring", 
        ["count"]=1
    }
}