-- Generated by the Organizer Library (02/17/18 19:05:54)
return {
    [1]={
        ["log_name"]="zha'go's barbut", 
        ["id"]=16159, 
        ["name"]="zha'go's barbut", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="drone earring", 
        ["id"]=13361, 
        ["name"]="drone earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="drone earring", 
        ["id"]=13361, 
        ["name"]="drone earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="blobnag ring", 
        ["id"]=11631, 
        ["name"]="blobnag ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="merman's earring", 
        ["id"]=13406, 
        ["name"]="merman's earring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="merman's earring", 
        ["id"]=13406, 
        ["name"]="merman's earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="genbu's kabuto", 
        ["id"]=12434, 
        ["name"]="genbu's kabuto", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="strigoi ring", 
        ["id"]=11628, 
        ["name"]="strigoi ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="triumph earring", 
        ["id"]=13408, 
        ["name"]="triumph earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="veela ring", 
        ["id"]=11634, 
        ["name"]="veela ring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="jelly ring", 
        ["id"]=13303, 
        ["name"]="jelly ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="hades earring +1", 
        ["id"]=14718, 
        ["name"]="hades earring +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="toreador's ring", 
        ["count"]=1, 
        ["id"]=14674, 
        ["name"]="toreador's ring", 
        ["augments"]={
            [1]="Accuracy+5", 
            [2]="\"Triple Atk.\"+2"
        }
    }, 
    [18]={
        ["log_name"]="toreador's ring", 
        ["count"]=1, 
        ["id"]=14674, 
        ["name"]="toreador's ring", 
        ["augments"]={
            [1]="\"Triple Atk.\"+2", 
            [2]="Accuracy+4"
        }
    }, 
    [19]={
        ["log_name"]="novia earring", 
        ["id"]=14809, 
        ["name"]="novia earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="maat's cap", 
        ["id"]=15194, 
        ["name"]="maat's cap", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="walahra turban", 
        ["id"]=15270, 
        ["name"]="walahra turban", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="cerberus ring +1", 
        ["id"]=15781, 
        ["name"]="cerberus ring +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="behemoth ring +1", 
        ["id"]=13556, 
        ["name"]="behemoth ring +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="corneus ring", 
        ["id"]=11630, 
        ["name"]="corneus ring", 
        ["count"]=1
    }
}