-- Generated by the Organizer Library (03/09/18 18:42:50)
return {
    [1]={
        ["log_name"]="dusk trousers", 
        ["id"]=12879, 
        ["name"]="dusk trousers", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="custom pants", 
        ["id"]=12872, 
        ["name"]="custom pants", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="commodore bottes", 
        ["id"]=11385, 
        ["name"]="comm. bottes", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="dusk ledelsens +1", 
        ["id"]=14188, 
        ["name"]="dusk ledelsens +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="cerberus mantle", 
        ["id"]=16212, 
        ["name"]="cerberus mantle", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="corsair's culottes", 
        ["id"]=15601, 
        ["name"]="corsair's culottes", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="commodore belt", 
        ["id"]=15920, 
        ["name"]="commodore belt", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="resolute belt", 
        ["id"]=15887, 
        ["name"]="resolute belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="commodore culottes", 
        ["id"]=16349, 
        ["name"]="comm. culottes", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="commander's cape", 
        ["id"]=13695, 
        ["name"]="commander's cape", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="velocious belt", 
        ["id"]=15899, 
        ["name"]="velocious belt", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="hermes' sandals", 
        ["id"]=11379, 
        ["name"]="hermes' sandals", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="enkidu's leggings", 
        ["id"]=11378, 
        ["name"]="enkidu's leggings", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="amemet mantle", 
        ["id"]=13645, 
        ["name"]="amemet mantle", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="corsair's bottes", 
        ["id"]=15685, 
        ["name"]="corsair's bottes", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="cuchulain's mantle", 
        ["id"]=16241, 
        ["name"]="cuchulain's mantle", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="crimson cuisses", 
        ["id"]=14280, 
        ["name"]="crimson cuisses", 
        ["count"]=1
    }
}